### ISSUE TITLE
Comment support

### ISSUE THREAD

**Issue by towerofnix** [liam4/programming-language-thing#2]
- [x] implement single line comments (https://github.com/liam4/programming-language-thing/commit/9fabd9e11a77ea9ed3b2f40cd421e65602d92c0b)
- [x] multi-line comments

What about multi/in-line comments?

``` python
#* comment *#
#: comment :#
#. comment .#
## comment ##
```

**Comment by towerofnix** [comment]
Probably going to go with `#: ff :#` - any objections?

**Comment by BookOwl** [comment]
I like `#: comment:#` best.

**Comment by bates64** [comment]
I like `## comment ##` for multiline comments.

**Comment by ghost** [comment]
I agree with Granny.

**Comment by BookOwl** [comment]
Did you decide if you're doing `#:` or `##`?

**Comment by towerofnix** [comment]
Nope :P

**Comment by BookOwl** [comment]
I still vote for `#:`

**Comment by plastpappa** [comment]
Hey, you should close this now. :package:

**Comment by towerofnix** [comment]
Multiline comment support added by @kvackkvack in #15 using syntax `#: ff :#`
