### ISSUE TITLE
Comparison/boolean operators

### ISSUE THREAD

**Issue by towerofnix** [liam4/programming-language-thing#6]
- [x] `gt(x y)` (greater than, `x > y`)
- [x] `lt(x y)` (less than, `x < y`)
- [x] `eq(x y)`
- [x] `not(x)`
- [x] `and(x y)`
- [x] `or(x y)`

**Comment by ghost** [comment]
I like them all. Would `(x y).gt` also be allowed?

**Comment by towerofnix** [comment]
@MrSherlockHolmes Depends on what `(x y)` is - as far as I know it's just a paren token, with no special properties.

**Comment by bates64** [comment]
Why is everything functional? :package:

**Comment by towerofnix** [comment]
Because I've always wanted to use a functional programming language :)

**Comment by ghost** [comment]
Heh :P I guess I like OOP

**Comment by BookOwl** [comment]
> Heh :P I guess I like OOP

I ~~hate~~ strongly dislike OOP.

**Comment by towerofnix** [comment]
> I strongly dislike OOP.

Why? :P

**Comment by bates64** [comment]
Both of you. Gitter. @liam4 @BookOwl
