### ISSUE TITLE
Change variable

### ISSUE THREAD

**Issue by towerofnix** [liam4/programming-language-thing#7]
Let's look at this code:

```
x -> 8
if(1 fn() {
    x -> 4
})
print(x)
```

It's output is `8`, but we'd like it to be `4`.

In order to do this, I'm thinking we can create a new behavior:

```
x -> 8
if(1 fn() {
    x -= 4
})
print(x)
# result is 4
```

`-=` changes, while `->` assigns. Simple enough? No immutability confusion like in JavaScript!

**Comment by liam4** [comment]
(cmd-enter auto post, sorryyyyyyy)

**Comment by towerofnix** [comment]
So now I've added that, but perhaps it would look better if `->` were change and `-=` were assign. Opinions?

**Comment by BookOwl** [comment]
`-=` looks like it decrements the variable. 
How about `=>` for assign and `->` for change?

**Comment by ghost** [comment]
That sounds good, BookOwl.

**Comment by towerofnix** [comment]
> `-=` looks like it decrements the variable.

Agreed, I noticed that..

I think I might go with `=>`/`->`, yes.

(doesn't mean input isn't wanted anymore)

**Comment by ghost** [comment]
COuld you add =- and =+ ? I've always had to use -= and += and they don't really look as good! :package:

**Comment by bates64** [comment]
@MrSherlockHolmes `var =- 1` could be confused with `var = -1`.

**Comment by ghost** [comment]
True.

**Comment by towerofnix** [comment]
See [Assign vs Change](https://github.com/liam4/programming-language-thing/blob/master/doc/Assign%20vs%20Change.md#assign-vs-change)
